### ISSUE TITLE
Fails at training

### ISSUE THREAD

**Issue by tonydavis629** [shacharp/Adaptive-LiDAR-Sampling#1]
I'm not able to get the main training script to run. Once the train and val sets are divided into the minisets, it comes back with a file not found error in ../data_new/ because it cannot find the 2011_xxx_ sync image in mini_set_1. I'm not sure what's going on with the data_new and miniset folders, can someone help me out?

**Comment by shacharp** [comment]
Fixed by adding or removing '/' in different places (for paths).
